version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  cooldown:
    default-days: 2
  schedule:
    interval: "daily"
  labels:
    - "dependencies"
  milestone: 5
  ignore:
    - dependency-name: io.github.git-commit-id:git-commit-id-maven-plugin
      update-types:
      - version-update:semver-major
    - dependency-name: org.junit.jupiter:*
      update-types:
      - version-update:semver-major
    - dependency-name: org.apache.groovy:*
      update-types:
      - version-update:semver-major

- package-ecosystem: "github-actions"
  directory: "/"
  cooldown:
    default-days: 2
  schedule:
    interval: "daily"
  milestone: 5
